config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :locations
  resources :users, only: [:edit, :update]
  devise_for :users
  
  resources :events
  root to: "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_url, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .actions
    = link_to 'Back', topics_path, class: 'btn btn-xs btn-default'
    = f.submit 'Save', class: 'btn btn-xs btn-primary'

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

app/views/topics/index.html.haml
%h1 Topics

%table.table
  %thead
    %tr
      %th Name
      %th Actions

  %tbody
    - @topics.each do |topic|
      %tr
        %td= topic.name
        %td
          = link_to 'Edit', edit_topic_path(topic), class: 'btn btn-xs btn-default'
          = link_to 'Delete', topic, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-xs btn-danger'

%br

= link_to 'New Topic', new_topic_path, class: 'btn btn-xs btn-default'

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

app/views/topics/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @topic.name

= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Back', topics_path