config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :locations
  resources :users, only: [:edit, :update]
  devise_for :users
  
  resources :events
  root to: "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  include Filtering

  after_create :notify_users_of_new_event

  belongs_to :location

  has_many :event_topics, dependent: :destroy
  has_many :topics, through: :event_topics

  validates_presence_of :name, :start_date, :end_date

  def notify_users_of_new_event
    User.with_location(location).with_topics(topics).each do |user|
      ApplicationMailer.notify_user_of_new_event(user, self).deliver
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.with_location(current_user.location).with_topics(current_user.topics).by_date(current_user.filter_date)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_date, :end_date, :location_id, topic_ids: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for(event) do |f|
  - if event.errors.any?
    #error_explanation
      %h2
        = pluralize(event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - event.errors.full_messages.each do |message|
          %li= message
  .row
    .col-xs-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .row
        .form-group.col-xs-6
          = f.label :start_date
          #datetimepicker1.input-group.date
            = f.text_field :start_date, class: "form-control", value: (f.object.start_date.strftime("%Y-%m-%d %R") unless f.object.new_record?)
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        .form-group.col-xs-6
          = f.label :end_date
          #datetimepicker2.input-group.date
            = f.text_field :end_date, class: "form-control", value: (f.object.start_date.strftime("%Y-%m-%d %R") unless f.object.new_record?)
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
      .row
        .form-group.col-xs-6
          = f.label :location_id
          = f.select :location_id, locations_for_select, class: "form-control"
        .form-group.col-xs-6
          = f.label :topics
          = f.collection_check_boxes(:topic_ids, Topic.all, :id, :name) do |topic|
            .checkbox
              = topic.label do |label|
                = topic.check_box
                = topic.object.name
    .form-group.col-xs-6
      = f.label :description
      = f.text_area :description, class: 'form-control', rows: 6
  .actions
    = link_to 'Back', events_path, class: 'btn btn-default btn-xs'
    = f.submit 'Save', class: 'btn btn-primary btn-xs'

app/views/events/edit.html.haml
%h1 Edit Event
= render 'form', event: @event

app/views/events/index.html.haml
%p#notice= notice
%h1 Events

%h3 Filter
= form_for(current_user) do |f|
  .row
    .col-xs-3
      .form-group
        = f.label :location_id
        = f.select :location_id, locations_for_select, class: "form-control", include_blank: true
      .form-group
        = f.label :filter_date, "Start Date"
        #datetimepicker3.input-group.date
          = f.text_field :filter_date, class: "form-control", value: (current_user.filter_date unless current_user.filter_date.blank?)
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar

    .form-group.col-xs-3
      = f.label :topics
      = f.collection_check_boxes(:topic_ids, Topic.all, :id, :name) do |topic|
        .checkbox
          = topic.label do |label|
            = topic.check_box
            = topic.object.name
    .actions.col-xs-3
      = f.submit "Filter", class: "btn btn-primary"

%br
%br
%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th Location
      %th Topics
      %th Start date
      %th End date
      %th Actions
  %tbody
    - @events.each do |event|
      %tr
        %td= event.name
        %td= event.description
        %td= event.location.try(:name)
        %td= event.topics.map(&:name).join(", ")
        %td= event.start_date.strftime("%Y-%m-%d %R") 
        %td= event.end_date.strftime("%Y-%m-%d %R")
        %td
          = link_to 'Edit', edit_event_path(event), class: 'btn btn-xs btn-default'
          = link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
%br/
= link_to 'New Event', new_event_path, class: 'btn btn-xs btn-default'

app/views/events/new.html.haml
%h1 New Event
= render 'form', event: @event