config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :locations
  resources :users, only: [:edit, :update]
  devise_for :users
  
  resources :events
  root to: "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_url, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to locations_url, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .actions
    = link_to 'Back', locations_path, class: "btn btn-xs btn-default"
    = f.submit 'Save', class: 'btn btn-xs btn-primary'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Locations

%table.table
  %thead
    %tr
      %th Name
      %th Actions

  %tbody
    - @locations.each do |location|
      %tr
        %td= location.name
        %td
          = link_to 'Edit', edit_location_path(location), class: "btn btn-xs btn-default"
          = link_to 'Delete', location, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-xs btn-danger"

%br

= link_to 'New Location', new_location_path, class: 'btn btn-xs btn-default'

app/views/locations/new.html.haml
%h1 New location

= render 'form'

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path